/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatLightLaf;
import modelos.CatupiryDecorator;
import modelos.CreamCheeseDecorator;
import modelos.IProduto;
import modelos.ProdutoBase;
import modelos.QueijoCheddarDecorator;

/**
 *
 * @author pcgamergab
 */
public class AdicionaisJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AdicionaisJDialog
     */
    public AdicionaisJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBox_Cheddar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox_CreamCheese = new javax.swing.JCheckBox();
        jCheckBox_Catupiry = new javax.swing.JCheckBox();
        jCheckBox_Nenhum = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionais");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox_Cheddar.setText("+ Cheddar");

        jLabel1.setText("Preço + 2,5");

        jCheckBox_CreamCheese.setText("Cream Cheese");

        jCheckBox_Catupiry.setText("Catupiry");

        jCheckBox_Nenhum.setText("Nenhum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_Cheddar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_CreamCheese))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_Catupiry))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_Nenhum)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBox_Cheddar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_CreamCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Catupiry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Nenhum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
   public IProduto obterProdutoComAdicionaisDoDB(String nomeDoProduto, double precoDoProduto, String descricaoDoProduto) {
    // Recupera os dados básicos do produto
    IProduto produtoBase = new ProdutoBase(nomeDoProduto, precoDoProduto, descricaoDoProduto);

    // Adiciona os decoradores de acordo com os checkboxes selecionados
    if (jCheckBox_Cheddar.isSelected()) {
        produtoBase = new QueijoCheddarDecorator(produtoBase);
    }

    if (jCheckBox_CreamCheese.isSelected()) {
        produtoBase = new CreamCheeseDecorator(produtoBase);
    }

    if (jCheckBox_Catupiry.isSelected()) {
        produtoBase = new CatupiryDecorator(produtoBase);
    }

    // Adicione lógica para outros adicionais aqui

    return produtoBase;
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionaisJDialog dialog = new AdicionaisJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_Catupiry;
    private javax.swing.JCheckBox jCheckBox_Cheddar;
    private javax.swing.JCheckBox jCheckBox_CreamCheese;
    private javax.swing.JCheckBox jCheckBox_Nenhum;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
