/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatLightLaf;
import modelos.IProdutoCRUD;
import modelos.Produtos;
import controle.ProdutoControle;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author pcgamergab
 */
public class TelaCadastroDeProdutos extends javax.swing.JFrame {
    
    IProdutoCRUD produtoControle = null;
    DefaultTableModel model;
    
    /**
     * Creates new form TelaCadastroDeProdutos
     */
    
    public TelaCadastroDeProdutos()  {
        initComponents();
        produtoControle = new ProdutoControle();
        this.setLocationRelativeTo(this);
        model = (DefaultTableModel) jTable_Produtos.getModel();
        mostraDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Produto = new javax.swing.JTextField();
        jTextField_Descricao = new javax.swing.JTextField();
        jTextField_Preco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Adicionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Produtos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Codigo.setEditable(false);
        jTextField_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto:");

        jLabel2.setText("Código:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Preço");

        jButton_Adicionar.setText("Adicionar");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jButton2.setText("editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("voltar");

        jTable_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Descrição", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Produtos.setShowGrid(true);
        jTable_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Produtos);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        jButton1.setText("Relatorio Vendas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Preco)
                            .addComponent(jTextField_Descricao)
                            .addComponent(jTextField_Produto)
                            .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Adicionar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CodigoActionPerformed
    private void limparTela(){
        jTextField_Codigo.setText("");
        jTextField_Descricao.setText("");
        jTextField_Preco.setText("");
        jTextField_Produto.setText("");
    }
    private void mostraDados(){
            try {
      
      List<Produtos> produtos = produtoControle.ObterListagemDeProdutos();
      DefaultTableModel model =  (DefaultTableModel) jTable_Produtos.getModel();
      model.setNumRows(0);
      
      if(produtos.isEmpty()) return;
      for(int pos = 0; pos < produtos.size(); pos++){
      Produtos listaProdutos = produtos.get(pos);
         
     
        
        String[] linha = new String[4];
        
        linha[0]=  Integer.toString(listaProdutos.getId());
        linha[1]= listaProdutos.getNome();
        linha[2] = listaProdutos.getDescricao();
        linha[3] = Double.toString(listaProdutos.getPreco());
        
        
        
        //linha     
        model.addRow(linha);
      }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
    }
    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarActionPerformed
        // TODO add your handling code here:
         try {
            
             String nome = jTextField_Produto.getText();
             String descricao = jTextField_Descricao.getText();
             double preco = Double.parseDouble(jTextField_Preco.getText());
         
                    
            
            Produtos objproduto = new Produtos(nome, descricao, preco);
            
            produtoControle.Incluir(objproduto);
           mostraDados();
           limparTela();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
        
    }//GEN-LAST:event_jButton_AdicionarActionPerformed

    private void jTable_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProdutosMouseClicked
        // TODO add your handling code here:
         try {
            int numeroLinha = jTable_Produtos.getSelectedRow();
            
            List<Produtos> ObterListagemDeProdutos = null;
            ObterListagemDeProdutos = produtoControle.ObterListagemDeProdutos();
            Produtos i = ObterListagemDeProdutos.get(numeroLinha);

            jTextField_Codigo.setText(""+i.getId());
            jTextField_Produto.setText(""+i.getNome());
            jTextField_Descricao.setText(""+i.getDescricao());
            jTextField_Preco.setText(""+i.getPreco());
            

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jTable_ProdutosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            
            String nome = jTextField_Produto.getText();
            double preco = Double.parseDouble(jTextField_Preco.getText());
            String descricao = jTextField_Descricao.getText();
            int id = Integer.parseInt(jTextField_Codigo.getText());
            
            Produtos objproduto = new Produtos(nome, descricao, preco);
            
            produtoControle.Alterar(id,objproduto);
           mostraDados();
           limparTela();
           
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
           int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION ) {
            
                try {
                    int id = Integer.parseInt(jTextField_Codigo.getText());
                    
                        produtoControle.Deletar(id);
            
                    mostraDados();           
                    limparTela();
        
                } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
        } 
           
        } else {
            
        }
           
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            TelaRelatorioVendas vendas = new TelaRelatorioVendas();
            vendas.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroDeProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                    new TelaCadastroDeProdutos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Produtos;
    private javax.swing.JTextField jTextField_Codigo;
    private javax.swing.JTextField jTextField_Descricao;
    private javax.swing.JTextField jTextField_Preco;
    private javax.swing.JTextField jTextField_Produto;
    // End of variables declaration//GEN-END:variables
}
